CREATE DATABASE blueprint
GO

USE blueprint
GO

CREATE TABLE Tipo_cliente(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(100) NOT NULL
)
GO

CREATE TABLE Clientes(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Razon_social VARCHAR(100) NOT NULL,
	Cuit VARCHAR(11) NOT NULL UNIQUE,
	ID_tipo INT NOT NULL FOREIGN KEY REFERENCES Tipo_cliente(ID),
	Email VARCHAR(50) NULL,
	Telefono VARCHAR(20) NULL,
	Celular VARCHAR(20) NULL
)
GO

CREATE TABLE Proyectos(
	ID VARCHAR(5) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	Descripcion TEXT NULL,
	ID_cliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(ID),
	Fecha_inicio DATE NOT NULL,
	Fecha_fin DATE NULL,
	Costo MONEY NOT NULL,
	Estado BIT NOT NULL 
)